apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: massage-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP
